### PR TITLE
Drop sentences refering homu.io and add to refer bors.tech.

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/voyagegroup/popuko/issues/243

homu.io has been closed for a long time.
We should refer a living service to guide the alternative.

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 63ffb9d75bc382453aea73d9a9a0e0a8369a1013 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 63ffb9d75bc382453aea73d9a9a0e0a8369a1013 has been merged into the auto branch b49fc6b5ae6e4e9323012d4f213246457ea8c0de

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/296064091?utm_source=github_status&utm_medium=notification)

**Pull request merged**
