### PR TITLE
Replace CI workflow with GitHub Actions

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
* This PR is intend to replace TravisCI
* After we merge this PR, I seem we need to disconnect from TravisCI by this repository setting and TravisCI's console.

### CODE REVIEW

**Comment by mitsukavg** [comment]
LGTM~~~~

**Comment by ara-ta3** [comment]
@popuko r+

**Comment by mitsukavg** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 4ea79856f1999622540c2bd0002f1d997686ff56 has been approved by `mitsukavg`

**Comment by popuko** [comment]
:hourglass: 4ea79856f1999622540c2bd0002f1d997686ff56 has been merged into the auto branch 5137504dd760cef9ed1c0d503d8183789a284499

**Comment by tetsuharuohzeki** [comment]
@mitsukavg @ara-ta3 Thank you!

**Pull request merged**
