### PR TITLE
fix typo and deadlink

### PR DESCRIPTION
**Pull request by thekuwayama**
Hi!

This PR fixes typo and deadlink.
Thanks.

### CODE REVIEW

**Comment by saneyuki** [comment]
Thank you!

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 3fc636311c7a5b0204f942b1f8ab6a43178f7b1b has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 3fc636311c7a5b0204f942b1f8ab6a43178f7b1b has been merged into the auto branch 11df327ead4638ccae8a44fc48ed0bc087b5f4b5

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/539078396?utm_source=github_status&utm_medium=notification)

**Pull request merged**
