### PR TITLE
Add a new permission role who only can merge their pull request

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/voyagegroup/popuko/issues/237

------------

Users in `mergeable_users` in OWNERS.json can merge only a pull request opened by themselves.

They only can command `@<botname> r=<reviewer_name>` and `<reviewer_name>`
must be different from their names.

---
This change is [Reviewable](https://reviewable.io/reviews/voyagegroup/popuko/239)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/voyagegroup/popuko/239)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 6b4e8a7f652a5bbe9e2972f813d78b8463c86f57 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 6b4e8a7f652a5bbe9e2972f813d78b8463c86f57 has been merged into the auto branch 28db5fa4b1eeee23e8417e1f51731ee8df6422c3

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/229833824?utm_source=github_status&utm_medium=notification)

**Pull request merged**
