### PR TITLE
Omae mo rou-ningyo ni

### PR DESCRIPTION
**Pull request by nekoya**
fc

### CODE REVIEW

**Comment by nishigori** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 89562347828f8e621b9edd101a8390812588b835 has been approved by `nishigori`

**Comment by popuko** [comment]
:hourglass: 89562347828f8e621b9edd101a8390812588b835 has been merged into the auto branch 7724d3b19925b4b6a25b411ca47e261de0cf0823

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/437461487?utm_source=github_status&utm_medium=notification)

**Comment by saneyuki** [comment]
🏆

**Pull request merged**
