### PR TITLE
support github enterprise

### PR DESCRIPTION
**Pull request by takaishi**
Hello, 

I will support GitHub Enterprise because I try this on our GHE environment.

Thanks.

### CODE REVIEW

**Comment by saneyuki** [comment]
I'm sorry this reply is late. I seem this patch would work. 

Thank you for your contribution.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit f1c14baf67db094f732c9884e66897e3297afbf1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: f1c14baf67db094f732c9884e66897e3297afbf1 has been merged into the auto branch dab299680e77aef59e48f97ac90365432c350462

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/498804263?utm_source=github_status&utm_medium=notification)

**Pull request merged**
