### PR TITLE
Upgrade Go toolchain to v1.13

### PR DESCRIPTION
**Pull request by saneyuki**
This change includes:

1. Upgrade Go toolchain to v1.13.
2. Move to Go Module from `dep`.
3. Upgrade go-github to the latest.

Of course, I agree that the pull request which combines some changes is ugly.
But I push these changes into this single PR to ensure the baseline because:

1. I cannot trust that old go-github works with Go v1.13. They does not test their code with old Go toolchains.
2. With Go v1.13, we can migrate easily from `dep` to Go Module.

### CODE REVIEW

**Comment by nekoya** [comment]
I confirmed the changesets that contained in this PR, and succeeded build this branch with Go1.13.

This PR looks good to me, though I don't have enough confidence to merge it yet.

@mitsukavg Can we try to switch our Popuko container to this branch?

**Comment by mitsukavg** [comment]
ok, switched.

**Comment by nekoya** [comment]
@popuko r+

Works well

**Comment by popuko** [comment]
:pushpin: Commit 5376cf2d2ea4a0e703be1dd03dd37d9747cf70ab has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 5376cf2d2ea4a0e703be1dd03dd37d9747cf70ab has been merged into the auto branch 7ee9f377b10ca66f757eb992bea40dd970a44ca7

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/586876589?utm_source=github_status&utm_medium=notification)

**Comment by saneyuki** [comment]
Thank you!

**Comment by saneyuki** [comment]
@nekoya @mitsukavg Thank you!

**Pull request merged**
