### PR TITLE
Drop to support Golang 1.8 

### PR DESCRIPTION
**Pull request by saneyuki**
This pull request depends on https://github.com/voyagegroup/popuko/pull/242

### CODE REVIEW

**Comment by nekoya** [comment]
@saneyuki r=me

**Comment by popuko** [comment]
:pushpin: Commit 3cc0d133aaff02dd5dbab197b225f70bf61fa2ed has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 3cc0d133aaff02dd5dbab197b225f70bf61fa2ed has been merged into the auto branch 0b4c8072624e982657a5eeee5d628ada7641a8f5

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/308833499?utm_source=github_status&utm_medium=notification)

**Pull request merged**
