### PR TITLE
Don't assign a revirewer on an issue.

### PR DESCRIPTION
**Pull request by saneyuki**
## Motivation

I seem it's better to do it only on a pull request.

## Drawback

We cannot do `r? @username` on an issue to ask them about their feedback after merging this.
But I think it's a trivial problem which does not consume much human's time.

## Related Issue

_ I found the problem on https://github.com/voyagegroup/eslint-config-fluct/issues/115
- This depends on https://github.com/voyagegroup/popuko/pull/242

### CODE REVIEW

**Comment by nekoya** [comment]
@saneyuki r=me

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit a4b3b3e44731c1eb5c2a86d5196b5a3365ea33fc has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: a4b3b3e44731c1eb5c2a86d5196b5a3365ea33fc has been merged into the auto branch 5ffe42a7612939e6348f1c10599ae20ce3540d58

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/308831889?utm_source=github_status&utm_medium=notification)

**Comment by nekoya** [comment]
Ah, didn't need to rebase.

**Pull request merged**
