### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
## Changes

- https://github.com/BurntSushi/toml/compare/b26d9c308763d68093482582cea63d69be07a0f0...a368813c5e648fee92e5f6c30e3944ff9d5e8895
- https://github.com/google/go-github/compare/de33c46a823d3f723514fc5333b75ef2e937b7df...e7bb4b8ce29fb7beaf0765acda602bc516a56dd5

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 67948e72b61c8c40a88ad7b52d7b0af1e0483ea5 has been approved by `nekoya`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@nekoya I feel popuko is deadlocking now... 😢

**Comment by nekoya** [comment]
@popuko r=me

**Comment by popuko** [comment]
:pushpin: Commit 67948e72b61c8c40a88ad7b52d7b0af1e0483ea5 has been approved by `me`

**Comment by popuko** [comment]
:hourglass: 67948e72b61c8c40a88ad7b52d7b0af1e0483ea5 has been merged into the auto branch 24dd236c1d7f3a251c09168dd554794a2848be15

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/355769811?utm_source=github_status&utm_medium=notification)

**Pull request merged**
