### PR TITLE
Replace 'karen-irc' to 'voyagegroup' for transferring

### PR DESCRIPTION
**Pull request by saneyuki**
Related to https://github.com/voyagegroup/popuko/issues/235

---
This change is [Reviewable](https://reviewable.io/reviews/voyagegroup/popuko/236)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/voyagegroup/popuko/236)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 643e444111ef4f07fd679ed30ad35bdb7ae3f071 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 643e444111ef4f07fd679ed30ad35bdb7ae3f071 has been merged into the auto branch 5146fa4f56684de90cc7d2fe476a192a54932c53

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/223826910)

**Pull request merged**
