### PR TITLE
Upgrade the supported golang to v1.10.x

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 6f9cee97157dc6af0e5937c9dd0af30c1eb8f524 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 6f9cee97157dc6af0e5937c9dd0af30c1eb8f524 has been merged into the auto branch 03e5448b429a291979d453c7ec08f69f1183aba8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/355751089?utm_source=github_status&utm_medium=notification)

**Pull request merged**
