### PR TITLE
Upgrade Go toolchain to v1.14

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
* [Blog](https://blog.golang.org/go1.14)
* [Release Note](https://golang.org/doc/go1.14)

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0f7c8270e87149e16fc284c9899b225d922eaa96 has been approved by `nekoya`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: 0f7c8270e87149e16fc284c9899b225d922eaa96 has been merged into the auto branch a6372003c754810490e101920dbea65b296763ef

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/github/voyagegroup/popuko/builds/677565455?utm_source=github_status&utm_medium=notification)

**Pull request merged**
