### PR TITLE
Separate the path to accept changesets

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/voyagegroup/popuko/238)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 9ea16abc4bdc5add5bfce4d1cb5a0253783816e2 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 9ea16abc4bdc5add5bfce4d1cb5a0253783816e2 has been merged into the auto branch 56edde66655a5af288b1d4b8166e5f8a0a127114

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 9ea16abc4bdc5add5bfce4d1cb5a0253783816e2 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 9ea16abc4bdc5add5bfce4d1cb5a0253783816e2 has been merged into the auto branch 56edde66655a5af288b1d4b8166e5f8a0a127114

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/227886713?utm_source=github_status&utm_medium=notification)

**Pull request merged**
