### PR TITLE
Welcome nishigori

### PR DESCRIPTION
**Pull request by nekoya**
The guy, better golang reviewer, especially around dep.

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r=me

**Comment by saneyuki** [comment]
@nekoya 

I seem popuko does not subscribe this repository now.

**Comment by nekoya** [comment]
@popuko r=me

**Comment by popuko** [comment]
:pushpin: Commit 12f5a185ec1c13ee22af8dd08e4f719d8e59befe has been approved by `me`

**Comment by popuko** [comment]
:hourglass: 12f5a185ec1c13ee22af8dd08e4f719d8e59befe has been merged into the auto branch cbc2ef9aa4d017d5346e0ba9806348448e17dc56

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/437459817?utm_source=github_status&utm_medium=notification)

**Comment by saneyuki** [comment]
🎉

**Pull request merged**
