### PR TITLE
Allow to compile with Go1.9 & the latest dep

### PR DESCRIPTION
**Pull request by saneyuki**
I worked this pull request with
- go 1.9
- [dep](https://github.com/golang/dep/commit/28fb6b0f0b53e46e89a047f63575e56a3600cecd)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya 

Sorry, I did not push the complete changeset.
I've pushed them now. So could you review this?

**Comment by nekoya** [comment]
Ah, I have to confirm this, sorry.

**Comment by nekoya** [comment]
@popuko r+

Sorry for late, I had to rebuild my golang environment.

I replaced our working binary called as PAAS (Popuko As A Service).

**Comment by popuko** [comment]
:pushpin: Commit 288b8c20c3f97a42b07740db0b21f55a6d852564 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 288b8c20c3f97a42b07740db0b21f55a6d852564 has been merged into the auto branch 10f8420f971858eb78a63785aedb56f988e8b37a

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/308819071?utm_source=github_status&utm_medium=notification)

**Pull request merged**
