### PR TITLE
Check the head's sha before mergeing the pull request

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
- Retry https://github.com/karen-irc/popuko/pull/145
- #105

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/148)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0bd23764ff1bd3f48be254636ac731d0050afa09 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 0bd23764ff1bd3f48be254636ac731d0050afa09 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/5aa52d6150ea9c03f8f0c72b5473bcb4f2737395

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189391787)

**Pull request merged**
