### PR TITLE
Rename my Github id to new one in OWNERS.json

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
I renamed my github id. My contribution would continue to be less
perhaps.

But I'd like to keep me as a reviewer to react newbiew contributors if you could not react.

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c25de6c8c71a5f2dd3d33842ee31763362a9c1fe has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: c25de6c8c71a5f2dd3d33842ee31763362a9c1fe has been merged into the auto branch 80a8bea6462248a976be0c6b107cdbcd2a3297b8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/github/voyagegroup/popuko/builds/677564612?utm_source=github_status&utm_medium=notification)

**Pull request merged**
