### PR TITLE
Update Gopkg.lock for the compatibility with dep 0.5

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nishigori** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 5ac46fd678a9b55b3d5a03d68b8b7e3cd549d265 has been approved by `nishigori`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/popuko/builds/446007211?utm_source=github_status&utm_medium=notification)

**Pull request merged**
